#!/bin/bash

if [ -n "${KEYSTORE_PATH}" ] && [ -n "${KEYSTORE_PASSWORD}" ] && [ -n "${ALIAS}" ] && [ -n "${ALIAS_PASSWORD}" ]; then
	/jiagu/java/bin/apksigner sign --ks ${KEYSTORE_PATH} --ks-pass "env:KEYSTORE_PASSWORD" --ks-key-alias ${ALIAS} --key-pass "env:ALIAS_PASSWORD" $@
else
	/jiagu/java/bin/apksigner sign $@
fi